version: '{build}'
image: Visual Studio 2017
environment:
  NUGETAPIKEY:
    secure: Ev6JfzK7FYZzsR4ALWtJs95U98Pa9FxgMxECDA0LGNidWwULyKoQIKYQwMVZ1s0U
  BUILD_BOT_PASSWORD:
    secure: wJ9JVS5hSAp9ItYlHKxTPg==
build_script:
- ps: .\build.ps1 --target=NuGetPublish """--trigger=$env:APPVEYOR_REPO_TAG_NAME""" "--nugetApiKey=$env:NUGETAPIKEY"
test: off
artifacts:
- path: 'release\*.nupkg'
